version: 2

models:
  - name: violation_analysis
    description: "Analyzes the frequency and type of traffic violations."
    columns:
      - name: Violation_Description
        description: "Description of the traffic violation."
      - name: Total_Violations
        description: "Total number of specific violations."

  - name: gender_analysis
    description: "Breakdown of traffic violations by gender."
    columns:
      - name: Gender
        description: "Gender of the person who received the traffic ticket."
      - name: Violation_Count
        description: "Count of violations by gender."

  - name: age_group_analysis
    description: "Analyzes traffic violations by age groups."
    columns:
      - name: Age_Group
        description: "Categorization of age groups (e.g., 'Under 20', '20-40', 'Above 40')."
      - name: Total_Violations
        description: "Total violations occurring within each age group."

  - name: ticket_source_analysis
    description: "Evaluates the source systems processing the tickets."
    columns:
      - name: Source
        description: "Source system of the ticket (e.g., TSLED, TVB)."
      - name: Ticket_Count
        description: "Number of tickets processed by each source."
