version: 2

models:
  - name: stg_property_tax_rates
    description: >
      This staging model prepares the raw `property_tax_rates` data for analysis.
      It removes duplicates, standardizes column formats, and ensures data quality.
    columns:
      - name: fiscal_year_ending
        description: "The fiscal year in which the data applies."
        tests:
          - not_null
      - name: roll_year
        description: "The roll year associated with the fiscal year."
        tests:
          - not_null
      - name: swis_code
        description: "The SWIS code identifying the municipality."
      - name: municipality
        description: "The name of the municipality where the tax applies."
        tests:
          - not_null
      - name: county
        description: "The county where the municipality is located."
        tests:
          - not_null
      - name: school_code
        description: "The unique code identifying the school district."
      - name: school_name
        description: "The name of the school district."
      - name: type_of_value_on_which_tax_rates_are_applied
        description: "The type of value used as the basis for calculating tax rates (e.g., assessed value)."
      - name: county_tax_levy
        description: "The total county tax levy amount."
        tests:
          - not_null
          - numeric
      - name: county_tax_rate_outside_village_per_1000_assessed_value
        description: "The county tax rate outside village per $1000 of assessed value."
        tests:
          - numeric
      - name: county_tax_rate_inside_village_per_1000_assessed_value
        description: "The county tax rate inside village per $1000 of assessed value."
        tests:
          - numeric
      - name: municipality_tax_levy
        description: "The total municipal tax levy amount."
        tests:
          - numeric
      - name: municipal_tax_rate_outside_village_per_1000_assessed_value
        description: "The municipal tax rate outside village per $1000 of assessed value."
        tests:
          - numeric
      - name: municipal_tax_rate_inside_village_per_1000_assessed_value
        description: "The municipal tax rate inside village per $1000 of assessed value."
        tests:
          - numeric
      - name: school_district_tax_levy
        description: "The total school district tax levy amount."
        tests:
          - not_null
          - numeric
      - name: school_district_tax_rate_per_1000_assessed_value
        description: "The school district tax rate per $1000 of assessed value."
        tests:
          - numeric
